### ISSUE TITLE
Verifying installation with demo example ends with KeyError

### ISSUE THREAD

**Issue by shoepfl** [lanl/PyBNF#312]
I installed PyBNF and Bionetgen on my windows computer without any problems or errors.

However, when I want to verify my installation with pybnf -c demo_xml.conf, I get the error:

Sorry, an unknown error occurred: KeyError: 'step'
Logs have been saved to bnf_20211208-141351.log.
Please report this bug to help us improve PyBNF.

Can someone tell me if the problem is on my installation or on the demo example?

Many thanks in advance.

**Comment by wshlavacek** [comment]
Thanks for letting us know about this error message
There’s a problem in the CONF file 
The fix is to add a time step to the simulation command 
So… your installation is probably fine

**Comment by wshlavacek** [comment]
The CONF file has been fixed.

**Comment by shoepfl** [comment]
Thank you very much for the fast response and the fix
