### ISSUE TITLE
error during test with example egfr_nf

### ISSUE THREAD

**Issue by nchorton** [lanl/PyBNF#325]
Hello,
I'm just starting to use bionetfit and had it installed on our HPC computers. The demo tests ran fine, but I've had trouble with some other examples and I don't understand the errors.
With egfr_nf.conf, I get an error and this log file:

![egfr_nf_logfile](https://user-images.githubusercontent.com/125530954/219267075-5dfe314b-ed43-4642-b8ae-1eb4e00a6419.jpg)

Thanks!

**Comment by wshlavacek** [comment]
I get the same errorWe need to figure out what’s wrongThis job worked fine in the past and the job setup files haven’t changed Sent from my iPhoneOn Feb 15, 2023, at 9:16 PM, nchorton ***@***.***> wrote:﻿
Hello,
I'm just starting to use bionetfit and had it installed on our HPC computers. The demo tests ran fine, but I've had trouble with some other examples and I don't understand the errors.
With egfr_nf.conf, I get an error and this log file:

Thanks!

**Comment by wshlavacek** [comment]
The problem I found was that the definition of the Clusters observable is incompatible with BioNetGen version 2.8.4.
I don't know why the latest release of BioNetGen doesn't like the observable definition - I reported the issue to the BNG help list. 
I commented out the observable and redefined Clusters as a global function, Clusters(). This change required replacing "Clusters" with "Clusters()" in 4 function definitions. 
After these changes, the job runs.

**Comment by nchorton** [comment]
Hi Bill,

Should I reinstall PyBNF or install a patch?

Thanks,
Nancy

**Comment by wshlavacek** [comment]
Jacob updated PyBNF recently to fix several issuesYou should probably upgrade/re-installThe example problem you had trouble with is fixed - at the GitHub repo Sent from my iPhoneOn Feb 28, 2023, at 5:49 PM, nchorton ***@***.***> wrote:﻿
Hi Bill,

Should I reinstall PyBNF or install a patch?

Thanks,
Nancy
